// Simple Express server to serve the built Vite files from the `dist` directory.
// After running `npm run build`, this file is copied into `dist/` by the build script.
// Usage in Dockerfile:
//   RUN npm ci --production && npm run build
//   CMD ["node", "dist/server.js"]

const express = require('express');
const path = require('path');

const app = express();
const port = process.env.PORT || 3000;

const distPath = path.join(__dirname, 'dist');

// Serve static assets generated by Vite
app.use(express.static(distPath));

// For SPA: redirect all other routes to index.html
app.get('*', (_req, res) => {
  res.sendFile(path.join(distPath, 'index.html'));
});

app.listen(port, () => {
  /* eslint-disable no-console */
  console.log(`Frontend is running at http://localhost:${port}`);
});
